;; Colour theme for Emacs
(require 'color-theme)

(defun color-theme-zwz ()
  "Color theme derived from tty-dark.
  Source: http://www.emacswiki.org/emacs/zwz"
  (interactive)
  (color-theme-install
   '(color-theme-zwz
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "blue")
      (cursor-color . "red")
      (cursor-type . box)
      (foreground-color . "ivory2")
      (mouse-color . "black"))
     ((ispell-highlight-face . highlight)
      (list-matching-lines-face . bold)
      (tinyreplace-:face . highlight)
      (view-highlight-face . highlight))
     (default ((t (nil))))
     (italic ((t (:italic t :slant italic :foreground "BlanchedAlmond"))))
     (bold ((t (:weight bold))))
     (bold-italic ((t (:underline t :weight bold :slant italic))))
     (underline ((t (:underline t :foreground "green"))))
     (strike-through ((t (:strike-through t :foreground "blue"))))
     (box ((t (:box t :background "blue"))))
     (highlight ((t (:background "blue" :foreground "yellow"))))

     (calendar-today-face ((t (:underline t))))

     (completions-common-part ((t (:foreground "forest green"))))
     (completions-first-difference ((t (:bold t :weight bold :foreground "salmon"))))

     (diary-face ((t (:foreground "red"))))
     (fixed-pitch ((t (:family "courier"))))

     (font-lock-builtin-face ((t (:foreground "gold"))))
     (font-lock-comment-face ((t (:foreground "cyan3" :italic t :slant italic))))
     (font-lock-comment-delimiter-face ((t (:foreground "cyan3" :italic t :slant italic))))
     (font-lock-doc-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-constant-face ((t (:foreground "gold"))))
     (font-lock-function-name-face ((t (:bold t :foreground "white"))))
     (font-lock-keyword-face ((t (:foreground "brown2"))))
     (font-lock-string-face ((t (:foreground "LawnGreen"))))
     (font-lock-type-face ((t (:italic t :foreground "Orchid" :slant italic))))
     (font-lock-preprocessor-face ((t (:foreground "cyan4"))))
     (font-lock-reference-face ((t (:foreground "MediumPurple"))))
     (font-lock-variable-name-face ((t (:foreground "orange" :bold t))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :bold t))))

     (flymake-errline ((t (:underline "OrangeRed"))))
     (flymake-warnline ((t (:underline "yellow"))))

     (w3m-link-numbering ((t (:background "blue" :foreground "white" :bold t))))

     (fringe ((t (:background "DarkSlateBlue"))))

     (holiday-face ((t (:background "cyan"))))

     (info-menu-header ((t (:bold t :family "Sans Serif" :foreground "tomato" :weight bold))))
     (info-node ((t (:italic t :bold t :foreground "gold" :slant italic :weight bold))))
     (info-xref ((t (:bold t :foreground "powder blue" :weight bold))))

     (message-cited-text-face ((t (:foreground "red"))))
     (message-header-cc-face ((t (:bold t :foreground "green"))))
     (message-header-name-face ((t (:foreground "green"))))
     (message-header-newsgroups-face ((t (:italic t :weight medium :foreground "yellow"))))
     (message-header-other-face ((t (:foreground "#b00000"))))
     (message-header-subject-face ((t (:foreground "green"))))
     (message-header-to-face ((t (:weight medium :foreground "green"))))
     (message-header-xheader-face ((t (:foreground "blue"))))
     (message-mml-face ((t (:foreground "green"))))
     (message-separator-face ((t (:foreground "blue"))))

     (help-argument-name ((t (:italic t :slant italic))))

     (ido-first-match-face ((t (:bold t :weight medium))))
     (ido-indicator-face ((t (:background "blue" :foreground "yellow" :width condensed))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir-face ((t (:foreground "green"))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))

     (modeline ((t (:background "azure" :foreground "blue"))))
     (modeline-buffer-id ((t (:background "white" :foreground "red"))))
     (modeline-mousable ((t (:background "white" :foreground "magenta"))))
     (modeline-mousable-minor-mode ((t (:background "white" :foreground "yellow"))))

     (region ((t (:background "white" :foreground "black"))))
     (zmacs-region ((t (:background "cyan" :foreground "black"))))

     (secondary-selection ((t (:background "blue"))))
     (show-paren-match-face ((t (:background "SlateBlue1"))))
     (show-paren-mismatch-face ((t (:background "magenta" :foreground "white")))))))


(eval-after-load "color-theme"
  (progn
    (setq color-theme-is-global nil)
    (when (window-system) ; needed for the first frame
      (color-theme-zwz))))

(add-hook 'after-make-frame-functions
	  '(lambda (f)
	     (with-selected-frame f
	       (if (window-system f)
		   (color-theme-zwz)
		 ;; (color-theme-emacs-nw)
		 ))))

(defun colour-theme-darkness ()
  "Color theme inspired by emacs colors when invoked with `--no-window-system'.
   Color theme by Suvayu Ali, created 2010-08-21. Still testing."
  (interactive)
  (color-theme-install
   '(colour-theme-darkness
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "blue")
      (cursor-color . "red")
      (foreground-color . "ivory2")
      (mouse-color . "black"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (browse-kill-ring-separator-face . bold)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (org-goto-interface . outline)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "ivory2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (border ((t (:background "blue"))))
     (box ((t (:background "blue" :box 1))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (calendar-today ((t (:underline t))))
     (calendar-today-face ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan1"))))
     (completions-annotations ((t (:italic t :slant italic :foreground "BlanchedAlmond"))))
     (completions-common-part ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :background "black" :stipple nil :foreground "forest green" :height 98))))
     (completions-first-difference ((t (:bold t :weight bold :foreground "salmon"))))
     (cursor ((t (:background "red"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
     (custom-button-unraised ((t (:underline t :foreground "green"))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "light blue"))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "light blue" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "pink" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "cyan1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "cyan1" :height 0.8))))
     (diary ((t (:foreground "yellow1"))))
     (diary-face ((t (:foreground "yellow1"))))
     (dired-directory ((t (:bold t :weight bold :foreground "white"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Red"))))
     (dired-header ((t (:italic t :slant italic :foreground "Orchid"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "gold"))))
     (dired-marked ((t (:bold t :weight bold :foreground "Red"))))
     (dired-perm-write ((t (:italic t :slant italic :foreground "cyan3"))))
     (dired-symlink ((t (:foreground "brown2"))))
     (dired-warning ((t (:bold t :weight bold :foreground "Red"))))
     (dropdown-list-face ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightyellow" :foreground "black" :height 98))))
     (dropdown-list-selection-face ((t (:foreground "black" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "unknown" :family "DejaVu Sans Mono" :background "purple" :height 98))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "courier"))))
     (flymake-errline ((t (:underline "OrangeRed"))))
     (flymake-warnline ((t (:underline "yellow"))))
     (font-lock-builtin-face ((t (:foreground "gold"))))
     (font-lock-comment-delimiter-face ((t (:italic t :foreground "cyan3" :slant italic))))
     (font-lock-comment-face ((t (:italic t :foreground "cyan3" :slant italic))))
     (font-lock-constant-face ((t (:foreground "gold"))))
     (font-lock-doc-face ((t (:foreground "LawnGreen"))))
     (font-lock-doc-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-function-name-face ((t (:bold t :foreground "white" :weight bold))))
     (font-lock-keyword-face ((t (:foreground "brown2"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "cyan4"))))
     (font-lock-reference-face ((t (:foreground "MediumPurple"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "LawnGreen"))))
     (font-lock-type-face ((t (:italic t :foreground "Orchid" :slant italic))))
     (font-lock-variable-name-face ((t (:bold t :foreground "orange" :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (fringe ((t (:background "DarkSlateBlue"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic :foreground "BlanchedAlmond" :slant))))
     (highlight ((t (:background "blue" :foreground "yellow"))))
     (holiday ((t (:background "chocolate4"))))
     (holiday-face ((t (:background "chocolate4"))))
     (ido-first-match-face ((t (:weight medium))))
     (ido-indicator-face ((t (:background "blue" :foreground "yellow" :width condensed))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir-face ((t (:foreground "green"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "gold"))))
     (info-header-xref ((t (:bold t :weight bold :foreground "powder blue"))))
     (info-menu-5 ((t (:foreground "red1"))))
     (info-menu-header ((t (:bold t :family "Sans Serif" :foreground "tomato" :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "gold" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
     (info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
     (info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-xref ((t (:bold t :foreground "powder blue" :weight bold))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (iswitchb-current-match ((t (:bold t :weight bold :foreground "white"))))
     (iswitchb-invalid-regexp ((t (:bold t :weight bold :foreground "Red"))))
     (iswitchb-single-match ((t (:italic t :slant italic :foreground "cyan3"))))
     (iswitchb-virtual-matches ((t (:foreground "gold"))))
     (italic ((t (:italic t :foreground "BlanchedAlmond" :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (message-cited-text-face ((t (:foreground "red"))))
     (message-header-cc-face ((t (:bold t :foreground "green" :weight bold))))
     (message-header-name-face ((t (:foreground "green"))))
     (message-header-newsgroups-face ((t (:italic t :foreground "yellow" :slant italic :weight medium))))
     (message-header-other-face ((t (:foreground "#b00000"))))
     (message-header-subject-face ((t (:foreground "green"))))
     (message-header-to-face ((t (:foreground "green" :weight medium))))
     (message-header-xheader-face ((t (:foreground "blue"))))
     (message-mml-face ((t (:foreground "green"))))
     (message-separator-face ((t (:foreground "blue"))))
     (minibuffer-prompt ((t (:bold t :foreground "dark cyan" :weight bold))))
     (mode-line ((t (:background "azure" :foreground "blue" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (modeline-mousable ((t (:background "white" :foreground "magenta"))))
     (modeline-mousable-minor-mode ((t (:background "white" :foreground "yellow"))))
     (mouse ((t (:background "black"))))
     (next-error ((t (:foreground "black" :background "white"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (org-agenda-clocking ((t (:background "blue"))))
     (org-agenda-column-dateline ((t (:family "DejaVu Sans Mono" :weight normal :slant normal :underline nil :strike-through nil :background "grey30" :height 98))))
     (org-agenda-date ((t (:foreground "LightSkyBlue"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "LightSkyBlue" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (org-agenda-diary ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "ivory2" :background "black" :stipple nil :height 98))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:foreground "grey70"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:italic t :bold t :weight bold :slant oblique :foreground "DarkSeaGreen2" :background "ForestGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "thistle" :background "royalblue4"))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 98 :family "DejaVu Sans Mono"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-document-info ((t (:foreground "pale turquoise"))))
     (org-document-info-keyword ((t (:foreground "grey70"))))
     (org-document-title ((t (:bold t :foreground "pale turquoise" :weight bold :height 1.44))))
     (org-done ((t (:italic t :bold t :background "ForestGreen" :foreground "DarkSeaGreen2" :slant oblique :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:bold t :foreground "white" :weight bold))))
     (org-level-2 ((t (:bold t :foreground "orange" :weight bold))))
     (org-level-3 ((t (:foreground "brown2"))))
     (org-level-4 ((t (:italic t :foreground "cyan3" :slant italic))))
     (org-level-5 ((t (:italic t :foreground "Orchid" :slant italic))))
     (org-level-6 ((t (:foreground "gold"))))
     (org-level-7 ((t (:foreground "gold"))))
     (org-level-8 ((t (:foreground "LawnGreen"))))
     (org-link ((t (:foreground "Cyan" :underline t))))
     (org-meta-line ((t (:italic t :slant italic :foreground "cyan3"))))
     (org-mode-line-clock ((t (:box (:line-width -1 :style released-button) :foreground "blue" :background "azure"))))
     (org-mode-line-clock-overrun ((t (:box (:line-width -1 :style released-button) :foreground "blue" :background "red"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey70"))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "LightSalmon"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :background "royalblue4" :foreground "thistle" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70"))))
     (org-verse ((t (:foreground "grey70"))))
     (org-warning ((t (:bold t :weight bold :foreground "Red"))))
     (outline-1 ((t (:bold t :weight bold :foreground "white"))))
     (outline-2 ((t (:bold t :weight bold :foreground "orange"))))
     (outline-3 ((t (:foreground "brown2"))))
     (outline-4 ((t (:italic t :slant italic :foreground "cyan3"))))
     (outline-5 ((t (:italic t :slant italic :foreground "Orchid"))))
     (outline-6 ((t (:foreground "gold"))))
     (outline-7 ((t (:foreground "gold"))))
     (outline-8 ((t (:foreground "LawnGreen"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (rcirc-bright-nick ((t (:foreground "Aquamarine"))))
     (rcirc-dim-nick ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "ivory2" :background "black" :stipple nil :height 98))))
     (rcirc-keyword ((t (:foreground "yellow" :background "blue"))))
     (rcirc-my-nick ((t (:foreground "LightSkyBlue"))))
     (rcirc-nick-in-message ((t (:foreground "Cyan1"))))
     (rcirc-nick-in-message-full-line ((t (:bold t :weight bold))))
     (rcirc-other-nick ((t (:foreground "LightGoldenrod"))))
     (rcirc-prompt ((t (:foreground "cyan1"))))
     (rcirc-server ((t (:foreground "chocolate1"))))
     (rcirc-server-prefix ((t (:foreground "chocolate1"))))
     (rcirc-timestamp ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "ivory2" :background "black" :stipple nil :height 98))))
     (rcirc-track-keyword ((t (:bold t :weight bold))))
     (rcirc-track-nick ((t (nil))))
     (rcirc-url ((t (:bold t :weight bold))))
     (region ((t (:background "white" :foreground "black"))))
     (rst-level-1-face ((t (:background "grey85" :foreground "black"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "blue"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "SlateBlue1"))))
     (show-paren-mismatch ((t (:background "magenta" :foreground "white"))))
     (strike-through ((t (:foreground "blue" :strike-through t))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:foreground "green" :underline t))))
     (undo-tree-visualizer-active-branch-face ((t (:bold t :foreground "white" :weight bold))))
     (undo-tree-visualizer-current-face ((t (:foreground "red"))))
     (undo-tree-visualizer-default-face ((t (:foreground "gray"))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (w3m-link-numbering ((t (:bold t :background "blue" :foreground "white" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (woman-addition ((t (:foreground "gold"))))
     (woman-bold ((t (:bold t :weight bold :foreground "forest green"))))
     (woman-italic ((t (:italic t :slant italic :foreground "salmon"))))
     (woman-unknown ((t (:bold t :weight bold :foreground "Red"))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (zmacs-region ((t (:background "cyan" :foreground "black")))))))
(add-to-list 'color-themes '(colour-theme-darkness  "Darkness" "Suvayu Ali"))

;; Customise `basic-face'. Idea is to customise as little as
;; possible and Emacs choose the rest as it derives from basic face.

;; (defun color-theme-blue-mood ()
;;   "Color theme by Nelson Loyola, created 2002-04-15.
;; Includes cperl, custom, font-lock, p4, speedbar, widget."
;;   (interactive)
;;   (color-theme-install
;;    '(color-theme-blue-mood
;;      ((background-color . "DodgerBlue4")
;;       (background-mode . dark)
;;       (background-toolbar-color . "#bfbfbfbfbfbf")
;;       (border-color . "Blue")
;;       (border-color . "#000000000000")
;;       (bottom-toolbar-shadow-color . "#6c6c68686868")
;;       (cursor-color . "DarkGoldenrod1")
;;       (foreground-color . "white smoke")
;;       (mouse-color . "black")
;;       (top-toolbar-shadow-color . "#e5e5e0e0e1e1"))
;;      ((vc-annotate-very-old-color . "#0046FF"))
;;      (default ((t (nil))))
;;      (blue ((t (:foreground "blue"))))
;;      (bold ((t (:bold t))))
;;      (bold-italic ((t (nil))))
;;      (border-glyph ((t (nil))))
;;      (cmode-bracket-face ((t (:bold t))))
;;      (cperl-array-face ((t (:bold t :foreground "wheat"))))
;;      (cperl-hash-face ((t (:bold t :foreground "chartreuse"))))
;;      (custom-button-face ((t (nil))))
;;      (custom-changed-face ((t (:background "blue" :foreground "white"))))
;;      (custom-documentation-face ((t (nil))))
;;      (custom-face-tag-face ((t (:underline t))))
;;      (custom-group-tag-face ((t (:underline t :foreground "blue"))))
;;      (custom-group-tag-face-1 ((t (:underline t :foreground "red"))))
;;      (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
;;      (custom-modified-face ((t (:background "blue" :foreground "white"))))
;;      (custom-rogue-face ((t (:background "black" :foreground "pink"))))
;;      (custom-saved-face ((t (:underline t))))
;;      (custom-set-face ((t (:background "white" :foreground "blue"))))
;;      (custom-state-face ((t (:bold t :foreground "cyan"))))
;;      (custom-variable-button-face ((t (:underline t :bold t))))
;;      (custom-variable-tag-face ((t (:underline t :foreground "blue"))))
;;      (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue"))))
;;      (font-lock-builtin-face ((t (:bold t :foreground "wheat"))))
;;      (font-lock-comment-face ((t (:bold t :foreground "gray72"))))
;;      (font-lock-constant-face ((t (:bold t :foreground "cyan3"))))
;;      (font-lock-doc-string-face ((t (:foreground "#00C000"))))
;;      (font-lock-function-name-face ((t (:bold t :foreground "chartreuse"))))
;;      (font-lock-keyword-face ((t (:bold t :foreground "gold1"))))
;;      (font-lock-other-emphasized-face ((t (:bold t :foreground "gold1"))))
;;      (font-lock-other-type-face ((t (:bold t :foreground "gold1"))))
;;      (font-lock-preprocessor-face ((t (:foreground "plum"))))
;;      (font-lock-reference-face ((t (:bold t :foreground "orangered"))))
;;      (font-lock-string-face ((t (:foreground "tomato"))))
;;      (font-lock-type-face ((t (:bold t :foreground "gold1"))))
;;      (font-lock-variable-name-face ((t (:foreground "light yellow"))))
;;      (font-lock-warning-face ((t (:foreground "tomato"))))
;;      (green ((t (:foreground "green"))))
;;      (gui-button-face ((t (:background "grey75" :foreground "black"))))
;;      (gui-element ((t (:size "nil" :background "#e7e3d6" :foreground" #000000"))))
;;      (highlight ((t (:background "red" :foreground "yellow"))))
;;      (isearch ((t (:bold t :background "pale turquoise" :foreground "blue"))))
;;      (italic ((t (nil))))
;;      (lazy-highlight-face ((t (:bold t :foreground "dark magenta"))))
;;      (left-margin ((t (nil))))
;;      (list-mode-item-selected ((t (:bold t :background "gray68" :foreground "yellow"))))
;;      (modeline ((t (:background "goldenrod" :foreground "darkblue"))))
;;      (modeline-buffer-id ((t (:background "goldenrod" :foreground "darkblue"))))
;;      (modeline-mousable ((t (:background "goldenrod" :foreground "darkblue"))))
;;      (modeline-mousable-minor-mode ((t (:background "goldenrod" :foreground "darkblue"))))
;;      (my-tab-face ((t (:background "SlateBlue1"))))
;;      (p4-depot-added-face ((t (:foreground "steelblue1"))))
;;      (p4-depot-deleted-face ((t (:foreground "red"))))
;;      (p4-depot-unmapped-face ((t (:foreground "grey90"))))
;;      (p4-diff-change-face ((t (:foreground "dark green"))))
;;      (p4-diff-del-face ((t (:bold t :foreground "salmon"))))
;;      (p4-diff-file-face ((t (:background "blue"))))
;;      (p4-diff-head-face ((t (:background "blue"))))
;;      (p4-diff-ins-face ((t (:foreground "steelblue1"))))
;;      (paren-blink-off ((t (:foreground "DodgerBlue4"))))
;;      (paren-match ((t (:background "red" :foreground "yellow"))))
;;      (paren-mismatch ((t (:background "DeepPink"))))
;;      (pointer ((t (:background "white"))))
;;      (primary-selection ((t (:bold t :background "medium sea green"))))
;;      (red ((t (:foreground "red"))))
;;      (region ((t (:background "red" :foreground "yellow"))))
;;      (right-margin ((t (nil))))
;;      (secondary-selection ((t (:background "gray91" :foreground "sienna3"))))
;;      (show-paren-match-face ((t (:background "cyan3" :foreground "blue"))))
;;      (show-paren-mismatch-face ((t (:background "red" :foreground "blue"))))
;;      (show-trailing-whitespace ((t (:background "red" :foreground "blue"))))
;;      (speedbar-button-face ((t (:foreground "white"))))
;;      (speedbar-directory-face ((t (:foreground "gray"))))
;;      (speedbar-file-face ((t (:foreground "gold1"))))
;;      (speedbar-highlight-face ((t (:background "lightslateblue" :foreground "gold1"))))
;;      (speedbar-selected-face ((t (:underline t :foreground "red"))))
;;      (speedbar-tag-face ((t (:foreground "chartreuse"))))
;;      (text-cursor ((t (:background "DarkGoldenrod1" :foreground "DodgerBlue4"))))
;;      (toolbar ((t (:background "#e7e3d6" :foreground "#000000"))))
;;      (underline ((t (:underline t))))
;;      (vertical-divider ((t (:background "#e7e3d6" :foreground "#000000"))))
;;      (widget-button-face ((t (:bold t))))
;;      (widget-button-pressed-face ((t (:foreground "red"))))
;;      (widget-documentation-face ((t (:foreground "dark green"))))
;;      (widget-field-face ((t (:background "gray85"))))
;;      (widget-inactive-face ((t (:foreground "dim gray"))))
;;      (widget-single-line-field-face ((t (:background "gray85"))))
;;      (yellow ((t (:foreground "yellow"))))
;;      (zmacs-region ((t (:background "white" :foreground "midnightblue")))))))

;; (defun color-theme-late-night ()
;;   "Color theme by Alex Schroeder, created 2003-08-07.
;; This theme is for use late at night, with only little light in the room.
;; The goal was to make something as dark and subtle as the text console in
;; its default 80x25 state -- dark grey on black."
;;   (interactive)
;;   (let ((color-theme-is-cumulative t))
;;     (color-theme-dark-erc)
;;     (color-theme-dark-gnus)
;;     ;; (color-theme-dark-diff)
;;     ;; (color-theme-dark-eshell)
;;     (color-theme-dark-info)
;;     (color-theme-dark-font-lock)
;;     (color-theme-install
;;      '(color-theme-late-night
;;        ((background-color . "#000")
;; 	(background-mode . dark)
;; 	(background-toolbar-color . "#000")
;; 	(border-color . "#000")
;; 	(bottom-toolbar-shadow-color . "#000")
;; 	(cursor-color	. "#888")
;; 	(foreground-color . "#666")
;; 	(top-toolbar-shadow-color . "#111"))
;;        (default ((t (nil))))
;;        (bold ((t (:bold t))))
;;        (button ((t (:bold t))))
;;        (custom-button-face ((t (:bold t :foreground "#999"))))
;;        (fringe ((t (:background "#111" :foreground "#444"))))
;;        (header-line ((t (:background "#333" :foreground "#000"))))
;;        (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
;;        (holiday-face ((t (:background "#000" :foreground "#777"))))
;;        (isearch ((t (:foreground "pink" :background "red"))))
;;        (isearch-lazy-highlight-face ((t (:foreground "red"))))
;;        (italic ((t (:bold t))))
;;        (menu ((t (:background "#111" :foreground "#444"))))
;;        (minibuffer-prompt ((t (:foreground "555"))))
;;        (modeline ((t (:background "#111" :foreground "#444"))))
;;        (mode-line-inactive ((t (:background "#000" :foreground "#444"))))
;;        (modeline-buffer-id ((t (:background "#000" :foreground "#555"))))
;;        (modeline-mousable ((t (:background "#000" :foreground "#555"))))
;;        (modeline-mousable-minor-mode ((t (:background "#000" :foreground "#555"))))
;;        (region ((t (:background "dark cyan" :foreground "cyan"))))
;;        (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
;;        (show-paren-match-face ((t (:foreground "white" :background "light slate blue"))))
;;        (show-paren-mismatch-face ((t (:foreground "white" :background "red"))))
;;        (tool-bar ((t (:background "#111" :foreground "#777"))))
;;        (tooltip ((t (:background "#333" :foreground "#777"))))
;;        (underline ((t (:bold t))))
;;        (variable-pitch ((t (nil))))
;;        (widget-button-face ((t (:bold t :foreground "#888"))))
;;        (widget-field-face ((t (:bold t :foreground "#999"))))))))

;; (defun color-theme-mistyday ()
;;   "Color theme by K.C. Hari Kumar, created 2001-06-13.
;; Black on mistyrose.  Includes CUA, calendar, diary, font-latex and
;; font-lock.  Uses backgrounds on some font-lock faces."
;;   (interactive)
;;   (color-theme-install
;;    '(color-theme-mistyday
;;      ((background-color . "mistyrose")
;;       (background-mode . light)
;;       (border-color . "black")
;;       (cursor-color . "deep pink")
;;       (foreground-color . "Black")
;;       (mouse-color . "black"))
;;      ((goto-address-mail-face . italic)
;;       (goto-address-mail-mouse-face . secondary-selection)
;;       (goto-address-url-face . bold)
;;       (goto-address-url-mouse-face . highlight)
;;       (list-matching-lines-face . bold)
;;       (paren-match-face . paren-face-match)
;;       (paren-mismatch-face . paren-face-mismatch)
;;       (paren-no-match-face . paren-face-no-match))
;;     (default ((t (nil))))
;;     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
;;     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
;;     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
;;     (bold ((t (:bold t))))
;;     (bold-italic ((t (:italic t :bold t))))
;;     (calendar-today-face ((t (:underline t :background "Spring Green" :foreground "Brown"))))
;;     (custom-button-face ((t (:background "dark slate grey" :foreground "azure"))))
;;     (custom-documentation-face ((t (:background "white" :foreground "blue"))))
;;     (diary-face ((t (:background "navy" :foreground "yellow"))))
;;     (font-latex-bold-face ((t (:bold t :foreground "DarkOliveGreen"))))
;;     (font-latex-italic-face ((t (:italic t :foreground "DarkOliveGreen"))))
;;     (font-latex-math-face ((t (:foreground "navy"))))
;;     (font-latex-sedate-face ((t (:foreground "DimGray"))))
;;     (font-latex-string-face ((t (nil))))
;;     (font-latex-warning-face ((t (nil))))
;;     (font-lock-builtin-face ((t (:background "DarkTurquoise" :foreground "Navy"))))
;;     (font-lock-comment-face ((t (:italic t :foreground "royal blue"))))
;;     (font-lock-constant-face ((t (:background "pale green" :foreground "dark slate blue"))))
;;     (font-lock-doc-string-face ((t (:background "medium aquamarine" :foreground "deep pink"))))
;;     (font-lock-function-name-face ((t (:background "SpringGreen" :foreground "MidnightBlue"))))
;;     (font-lock-keyword-face ((t (:foreground "dark magenta"))))
;;     (font-lock-preprocessor-face ((t (:background "pale green" :foreground "dark slate blue"))))
;;     (font-lock-reference-face ((t (:background "DarkTurquoise" :foreground "Navy"))))
;;     (font-lock-string-face ((t (:background "medium aquamarine" :foreground "deep pink"))))
;;     (font-lock-type-face ((t (:background "steel blue" :foreground "khaki"))))
;;     (font-lock-variable-name-face ((t (:background "thistle" :foreground "orange red"))))
;;     (font-lock-warning-face ((t (:background "LemonChiffon" :foreground "Red"))))
;;     (highlight ((t (:background "dark slate grey" :foreground "light cyan"))))
;;     (holiday-face ((t (:background "orangered" :foreground "lightyellow"))))
;;     (ido-first-match-face ((t (:bold t))))
;;     (ido-only-match-face ((t (:foreground "ForestGreen"))))
;;     (ido-subdir-face ((t (:foreground "red"))))
;;     (italic ((t (:italic t))))
;;     (isearch ((t (:background "sienna" :foreground "light cyan"))))
;;     (modeline ((t (:background "Royalblue4" :foreground "lawn green"))))
;;     (modeline-buffer-id ((t (:background "Royalblue4" :foreground "lawn green"))))
;;     (modeline-mousable ((t (:background "Royalblue4" :foreground "lawn green"))))
;;     (modeline-mousable-minor-mode ((t (:background "Royalblue4" :foreground "lawn green"))))
;;     (paren-face-match ((t (:background "turquoise"))))
;;     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
;;     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
;;     (primary-selection ((t (:background "sienna" :foreground "light cyan"))))
;;     (region ((t (:background "sienna" :foreground "light cyan"))))
;;     (secondary-selection ((t (:background "forest green" :foreground "white smoke"))))
;;     (underline ((t (:underline t))))
;;     (zmacs-region ((t (:background "sienna" :foreground "light cyan")))))))

;; eta clean
;; (defun color-theme-feng-shui ()
;;   "Color theme by walterh@rocketmail.com (www.xanadb.com), created
;;   2003-10-16. Evolved from color-theme-katester"
;;   (interactive)
;;   (color-theme-install
;;    '(color-theme-feng-shui
;;      ((background-color . "ivory")
;;       (background-mode . light)
;;       (border-color . "black")
;;       (cursor-color . "slateblue")
;;       (foreground-color . "black")
;;       (mouse-color . "slateblue"))
;;      ((help-highlight-face . underline)
;;       (list-matching-lines-face . bold)
;;       (view-highlight-face . highlight)
;;       (widget-mouse-face . highlight))
;;      (default ((t (:stipple nil :background "ivory" :foreground "black"
;; :inverse-video nil :box nil :strike-through nil :overline nil
;; :underline nil :slant normal :weight normal :height 90 :width normal
;; :family "outline-courier new"))))
;;      (bold ((t (:bold t :weight bold))))
;;      (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
;;      (border ((t (:background "black"))))
;;      (cursor ((t (:background "slateblue" :foreground "black"))))
;;      (fixed-pitch ((t (:family "courier"))))
;;      (font-lock-builtin-face ((t (:foreground "black"))))
;;      (font-lock-comment-face ((t (:italic t :background "seashell"
;; :slant italic))))
;;      (font-lock-constant-face ((t (:foreground "darkblue"))))
;;      (font-lock-doc-face ((t (:background "lemonChiffon"))))
;;      (font-lock-function-name-face ((t (:bold t :underline t :weight
;; bold))))
;;      (font-lock-keyword-face ((t (:foreground "blue"))))
;;      (font-lock-string-face ((t (:background "lemonChiffon"))))
;;      (font-lock-type-face ((t (:foreground "black"))))
;;      (font-lock-variable-name-face ((t (:foreground "black"))))
;;      (font-lock-warning-face ((t (:bold t :foreground "Red" :weight
;; bold))))
;;      (fringe ((t (:background "grey95"))))
;;      (header-line ((t (:bold t :weight bold :underline t :background
;; "grey90" :foreground "grey20" :box nil))))
;;      (highlight ((t (:background "mistyRose" :foreground "black"))))
;;      (isearch ((t (:background "magenta4" :foreground
;; "lightskyblue1"))))
;;      (isearch-lazy-highlight-face ((t (:background "paleturquoise"))))
;;      (italic ((t (:italic t :slant italic))))
;;      (menu ((t (nil))))
;;      (mode-line ((t (:bold t :background "mistyRose" :foreground "navy"
;; :underline t :weight bold))))
;;      (mouse ((t (:background "slateblue"))))
;;      (region ((t (:background "lavender" :foreground "black"))))
;;      (scroll-bar ((t (nil))))
;;      (secondary-selection ((t (:background "yellow"))))
;;      (tool-bar ((t (:background "grey75" :foreground "black" :box
;; (:line-width 1 :style released-button)))))
;;      (trailing-whitespace ((t (:background "red"))))
;;      (underline ((t (:underline t))))
;;      (variable-pitch ((t (:family "helv"))))
;;      (widget-button-face ((t (:bold t :weight bold))))
;;      (widget-button-pressed-face ((t (:foreground "red"))))
;;      (widget-documentation-face ((t (:foreground "dark green"))))
;;      (widget-field-face ((t (:background "gray85"))))
;;      (widget-inactive-face ((t (:foreground "dim gray"))))
;;      (widget-single-line-field-face ((t (:background "gray85")))))))
